apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vidoer
  labels:
    app: {{ .Release.Name }}-vidoer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vidoer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vidoer
    spec:
      containers:
      - name: vidoer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}